version: "2"

linters:
  disable:
    - wsl
  enable:
    - wsl_v5
  settings:
    cyclop:
      max-complexity: 20
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/bwmarrin/discordgo
            - github.com/ledongthuc/pdf
            - github.com/modelcontextprotocol/go-sdk/mcp
            - github.com/pdfcpu/pdfcpu/pkg/api
            - github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model
            - github.com/pdfcpu/pdfcpu/pkg/pdfcpu/types
            - google.golang.org/genai
            - gopkg.in/yaml.v3
    funlen:
      lines: 90
      statements: 60
    gocognit:
      min-complexity: 35
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
