package main

import "time"

const (
	defaultConfigPath                    = "config.yaml"
	readyMessage                         = "bot is online"
	defaultExaSearchEndpoint             = "https://api.exa.ai/search"
	defaultExaMCPEndpoint                = "https://mcp.exa.ai/mcp?tools=web_search_exa"
	defaultSerpAPIGoogleLensEndpoint     = "https://serpapi.com/search.json"
	defaultTavilySearchEndpoint          = "https://api.tavily.com/search"
	defaultRentryEndpoint                = "https://rentry.co/"
	defaultStatusMessage                 = "github.com/jakobdylanc/llmcord"
	defaultMaxText                       = 100000
	defaultMaxImages                     = 5
	defaultMaxMessages                   = 25
	maxMessageNodes                      = 500
	registeredCommandCount               = 2
	maxAutocompleteChoices               = 25
	statusMessageMaxLength               = 128
	plainResponseMaxLength               = 4000
	streamingIndicator                   = " ..."
	unknownText                          = "Unknown"
	embedResponseMaxLength               = 4096 - len(streamingIndicator)
	embedColorComplete                   = 0x006400
	embedColorIncomplete                 = 0xffa500
	embedColorFailure                    = 0x8b0000
	modelCommandName                     = "model"
	modelCommandDescription              = "View or switch the current model"
	modelOptionName                      = "model"
	modelOptionDescription               = "Model to view or use"
	searchDeciderModelCommandName        = "searchdecidermodel"
	searchDeciderModelCommandDescription = "View or switch the current search decider model"
	searchDeciderModelOptionName         = "model"
	searchDeciderModelOptionDescription  = "Search decider model to view or use"
	showSourcesButtonCustomID            = "show_sources"
	showSourcesPageButtonCustomIDPrefix  = "show_sources_page:"
	showSourcesButtonLabel               = "Show Sources"
	showThinkingButtonCustomID           = "show_thinking"
	showThinkingPageButtonCustomIDPrefix = "show_thinking_page:"
	showThinkingButtonLabel              = "Show Thinking"
	showSourcesPreviousButtonLabel       = "Previous"
	showSourcesNextButtonLabel           = "Next"
	viewOnRentryButtonCustomID           = "view_on_rentry"
	viewOnRentryButtonLabel              = "View on Rentry"
	messageRoleAssistant                 = "assistant"
	finishReasonStop                     = "stop"
	finishReasonLength                   = "length"
	maxSearchQueries                     = 500
	defaultWebSearchMaxURLs              = 5
	exaSearchHighlightsMaxCharacters     = 4000
	maxYouTubeComments                   = 50
	showSourcesMessageMaxLength          = 1900
	showSourcesPageBodyMaxLength         = showSourcesMessageMaxLength - 64
	showThinkingUnavailableText          = "No thinking process available."
	showThinkingMessageMaxLength         = 1900
	showThinkingPageBodyMaxLength        = showThinkingMessageMaxLength - 64
	attachmentRequestTimeout             = 30 * time.Second
	attachmentDownloadMaxAttempts        = 3
	attachmentRetryBaseDelay             = 100 * time.Millisecond
	geminiFilePollInterval               = 500 * time.Millisecond
	geminiFileProcessingTimeout          = 2 * time.Minute
	openRouterHost                       = "openrouter.ai"
	openRouterTransformsField            = "transforms"
	openRouterMiddleOutTransform         = "middle-out"
	searchDeciderTimeout                 = 30 * time.Second
	facebookRequestTimeout               = 30 * time.Second
	tikTokRenderPollInterval             = 500 * time.Millisecond
	tikTokRenderTimeout                  = 2 * time.Minute
	tikTokRequestTimeout                 = 30 * time.Second
	webSearchTimeout                     = 30 * time.Second
	rentryRequestTimeout                 = 30 * time.Second
	redditRequestTimeout                 = 30 * time.Second
	websiteRequestTimeout                = 30 * time.Second
	youtubeRequestTimeout                = 30 * time.Second
	typingRefreshInterval                = 8 * time.Second
	editDelay                            = time.Second
	sseScannerInitialBuffer              = 64 * 1024
	sseScannerMaxBuffer                  = 1024 * 1024
	mappingNodePairSize                  = 2
	smallMapCapacity                     = 3
	tavilyResultFieldCapacity            = 4
	requestBodyBaseFields                = 3
	configuredModelParts                 = 2
)
